#ifndef TOMASCOMMANDLINETOOLS_GLOBAL_H
#define TOMASCOMMANDLINETOOLS_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(TOMASCOMMANDLINETOOLS_LIBRARY)
#  define TOMASCOMMANDLINETOOLS_EXPORT Q_DECL_EXPORT
#else
#  define TOMASCOMMANDLINETOOLS_EXPORT Q_DECL_IMPORT
#endif

#endif // TOMASCOMMANDLINETOOLS_GLOBAL_H
