#ifndef TOMASVIDEOREADER_GLOBAL_H
#define TOMASVIDEOREADER_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(TOMASVIDEOREADER_LIBRARY)
#  define TOMASVIDEOREADER_EXPORT Q_DECL_EXPORT
#else
#  define TOMASVIDEOREADER_EXPORT Q_DECL_IMPORT
#endif

#endif // TOMASVIDEOREADER_GLOBAL_H
